version: "3.7"
services:
  db:
    image: atf.intranet.bb.com.br:5001/postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loteria
